USE KRYPT;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ACCOUNTS')
BEGIN
	CREATE TABLE ACCOUNTS (ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL, USERNAME VARCHAR(255) NOT NULL,PASSWORD VARCHAR(255) NOT NULL,EMAIL_ADDRESS VARCHAR(255) NOT NULL,LAST_LOGIN VARCHAR(255) NOT NULL,ACCOUNT_KEY VARCHAR(255) NOT NULL)
END